RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts, except: [:index]
end

RedditClone/app/models/comment.rb
class Comment < ActiveRecord::Base
end

RedditClone/app/models/post.rb
class Post < ActiveRecord::Base
  validates :user, :title, :subs, presence: true

  belongs_to :sub,
  foreign_key: :sub_id,
  class_name: "Sub"

  belongs_to :user,
  foreign_key: :user_id,
  class_name: "User"

  has_many :postsubs,
  foreign_key: :post_id,
  class_name: "Postsub",
  inverse_of: :post


  has_many :subs,
  through: :postsubs,
  source: :sub

end

RedditClone/app/models/postsub.rb
class Postsub < ActiveRecord::Base

  belongs_to :sub,
  foreign_key: :sub_id,
  class_name: "Sub"

  belongs_to :post,
  foreign_key: :post_id,
  class_name: "Post"

end

RedditClone/app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :moderator, presence: true

  belongs_to :moderator,
  foreign_key: :user_id,
  class_name: "User"

  has_many :postsubs,
  foreign_key: :sub_id,
  class_name: "Postsub"

  has_many :posts,
  through: :postsubs,
  source: :post

end

RedditClone/app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}
  after_initialize :ensure_token
  attr_reader :password

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def valid_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.valid_password?(password)
    user
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  #I was using SELF here and it messed up the entire auth process while throwing no errors
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  def ensure_token
    self.session_token ||= User.generate_session_token
  end

end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

end

RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)

  end


  def edit
    @comment = Comment.find(params[:id])
    if @comment.author_id == current_user.id

    else
      flash.now[:errors]
    end
  end

  def update
    @comment = Comment.find(params[:id])

  end


  def destroy
    @comment = Comment.find(params[:id])

  end

  private

  def comment_params
    params.require(:comment).permit(:content, :author_id, :post_id)
  end


end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    debugger
    if @post.save!
      redirect_to sub_url(@post.sub_ids.first)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    if @post.user == current_user
      render :edit
    else
      flash.now[:errors] = ["Cannot edit another user's post"]
      render :show
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      render :show
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to sub_url(@post.sub_id)
    @post.destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids:[])
  end


end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password]
    )
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid Credentials, Try again."]
      render :new
    end
  end


  def destroy
    logout
    redirect_to subs_url
  end

end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def new
    render :new
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find(params[:id])
  end


  def create
    @sub = Sub.new(sub_params)
    @sub.moderator = current_user
    if @sub.save!
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end


  def edit
    @sub = Sub.find(params[:id])
    if @sub.moderator == current_user
      render :edit
    else
      flash.now[:errors] = ["You cannot edit a sub unless you're a moderator"]
      render :index
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      redirect_to edit_sub_url
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end


end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end

  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "All subs", subs_url %>
  <br>
  <% if logged_in? %>
    Welcome, <%= current_user.username %>
    <br>
    <form action="<%= session_url %>" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="Log out">
    </form>
  <% else  %>
    <a href=" <%= new_session_url  %> ">Log in</a>
    <a href=" <%= new_user_url  %> ">Register</a>
    <br>
  <% end %>


  <% if flash[:errors]%>
      <p><%= flash[:errors].join(", ") %></p>
    <% end %>

<%= yield %>

</body>
</html>

RedditClone/app/views/posts/edit.html.erb
Edit Post

<form action="<%= post_url(@post.id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
    <input type="hidden" name="post[sub_ids][]" value="">
  <label>
    Title:
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>
  <label>
    URL(optional):
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>
  <label>
    Content:
    <textarea name="post[content]" rows="8" cols="40"><%= @post.content %></textarea>
  </label>
    <br>
    Post to this following sub:
    <br>
    <% Sub.all.each do |sub| %>
      <input type="checkbox"
      name="post[sub_ids][]"
      value="<%= sub.id %>">
      <%= "checked" if post.sub_ids.include?(sub.id) %><%= sub.title %>
    <% end %>



  <input type="submit" name="" value="Edit post">

</form>

RedditClone/app/views/posts/new.html.erb
New Post

<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="post[sub_ids][]" value="">
  <label>
    Title:
    <input type="text" name="post[title]" value="">
  </label>
  <br>
  <label>
    URL(optional):
    <input type="text" name="post[url]" value="">
  </label>
  <br>
  <label>
    Content:
    <textarea name="post[content]" rows="8" cols="40"></textarea>
  </label>
    <br>
    Post to this following sub:
    <br>
    <% Sub.all.each do |sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%= sub.title %>
    <% end %>



  <input type="submit" name="" value="Make post">

</form>

RedditClone/app/views/posts/show.html.erb
<h1><%= @post.title  %> by <%= @post.user.username  %></h1>

<div class="Contentbox">
  Content:
  <br>
  <%= @post.content %>
</div>

  <% if @post.user == current_user %>
    <a href="<%= edit_post_url  %>">Edit Post</a>
  <% end %>

RedditClone/app/views/subs/edit.html.erb
Edit Sub

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">

  <label>
    Title:
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>
    Description:
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="" value="Save Edits">

RedditClone/app/views/subs/index.html.erb
<h1>All the subs are here</h1>
<ul>

  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.title %></a></li>
    <br>
  <% end %>

</ul>

RedditClone/app/views/subs/show.html.erb
 <h2>The <%= @sub.title %>  sub</h2>
<br>
Description:
<br>
<%= @sub.description %>
<br>
Moderator: <%= @sub.moderator.username %>

<% if @sub.moderator == current_user %>
    <a href="<%= edit_sub_url  %>">Edit sub</a>
  <% end %>

  <%= link_to "Make a Post", new_post_url %>

  <br>

  <% Post.all.each do |post| %>
    <% if post.sub_id == @sub.id %>
      <ul>
        <li><a href=" <%= post_url(post.id) %> "><%= post.title %></a></li>
      </ul>
    <% end %>
  <% end %>

  

RedditClone/app/views/users/new.html.erb
Create new Account

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Username:
    <input type="text" name="user[username]" value="">
  </label>

  <label>
    Password:
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Sign up">

</form>